### ISSUE TITLE
Trait method name conflict between DataTablesAjaxRequestTrait and FocSearchRequestTrait

### ISSUE THREAD

**Issue by rchavik** [allanmcarvalho/DataTables#10]
At this time, both traits uses `getDataTablesContent` as the ajax method name.

I think we should use a different name so that it's possible to use both traits in the same controller.

I can prepare a PR if you think this is desirable.

**Comment by allanmcarvalho** [comment]
I think it is very consistent. If you can do a PR to solve this. I'm grateful.
