### ISSUE TITLE
Cannot install on cakephp 3.6.x

### ISSUE THREAD

**Issue by joakim-emagine** [allanmcarvalho/DataTables#14]
Is it possible that you make a 3.6 branch?

**Comment by allanmcarvalho** [comment]
All you need is install 1.4.0. I changed de minimum version of cakephp on 1.5.0 because I was removed all depreciations from code.

**Comment by joakim-emagine** [comment]
Ok, I noted that but I wanted to get the updated bug fixes from 1.5.0 because since my is huge, I am slowly removing deprecations for 3.7. Also, note that 1.5.0 is fully compatible with 3.6.11+ which is why I asked for separate branch so  that the 1.4.0 can have bug fixes and enhancements as well, version numbers can be (eg. 1.4.1).

I got around this by installing the plugin manually, FYI.

Thanks, again for your hard work, great plugin.
