### ISSUE TITLE
How i can refresh the dataTable without reload the page?

### ISSUE THREAD

**Issue by emilianoLarrea** [allanmcarvalho/DataTables#17]

**Comment by joakim-emagine** [comment]
I had a similar issue, needed to update this line in the datatablesHelper.php
```php
     $readyFunctionContent .= "$('#" . $config['id'] . "').DataTable(";
```
to:
```php
     $readyFunctionContent .= $config['id'] . " = $('#" . $config['id'] . "').DataTable(";
```
Then I was able to reload via javascript: 
```javascript
datables_config_id.ajax.reload();
```

**Comment by allanmcarvalho** [comment]
You can get DataTables JS instance calling ``.DataTables();``

For example, to model Logs, the plugin will create te id '#dtLogs', you can create this function to reload table:

`<script>
    function reloadTable() {
        table = $('#dtLogs').DataTable();
        table.ajax.reload();
    };
</script>`

Obs.: You must call this function only after table loaded if not you will get an error.
