### ISSUE TITLE
Problem with implementation of datables initComplete

### ISSUE THREAD

**Issue by kaurotuan** [allanmcarvalho/DataTables#18]
Hello!

I'm trying to implement this param in loadComponent method on my cakephp controller, as you can read bellow:

'initComplete' => "function () { $('[data-toggle=confirmation]').confirmation({ rootSelector: '[data-toggle=confirmation]', }); }"

It returns this:

"initComplete": "function () { $('[data-toggle=confirmation]').confirmation({ rootSelector: '[data-toggle=confirmation]', }); }",

I´d like to receive this:

"initComplete": function () { $('[data-toggle=confirmation]').confirmation({ rootSelector: '[data-toggle=confirmation]', }); },

whithout the quotation marks.

Would it be possible to develop this change on cakephp-datatables?

**Comment by joakim-emagine** [comment]
add: %f% before "function" and after the "}". 
```php
'initComplete' => "%f%function () { 
$('[data-toggle=confirmation]').confirmation({ rootSelector: '[data-toggle=confirmation]', }); 
}%f%"
```

**Comment by kaurotuan** [comment]
It worked perfectly, thank you very much.
