### ISSUE TITLE
Add multiple buttons or anchor tags

### ISSUE THREAD

**Issue by veera1908** [allanmcarvalho/DataTables#19]
i need add two anchor links in action column (ex : edit, view). how can i add multiple buttons or anchor tags.
![screenshot-192 168 0 50-2019 03 06-09-44-05](https://user-images.githubusercontent.com/47779880/53855656-98d24d00-3ff4-11e9-9e78-16d3de1db56b.png)

**Comment by allanmcarvalho** [comment]
If you are using bootstrap framework find by btn-group css class. If you are using another framework find a similar solution.
