### ISSUE TITLE
Please help, cant make it work

### ISSUE THREAD

**Issue by victorpy** [allanmcarvalho/DataTables#2]
i follow the steps in "How to use" section. 
I think i did not understand well the step 4, i think that is why im getting an error. 
The error is 500 for "http://localhost:8765/users/get-data-tables-content/Users?draw=1&columns[0]...."
I dont have a function get-data-tables-content in my controller "users".
What can i be doing wrong?

**Comment by allanmcarvalho** [comment]
Hello,
You put "use DataTablesAjaxRequestTrait;" Before the "initialize ()" method?
It is responsible for implementing the "get-data-tables-content ()" method on the controller that will use the DataTable plugin.
Check this for me, and if the problem continues, try to provide me with more information as well as feedbacks.
Thank you!

```
use DataTablesAjaxRequestTrait;
 public function initialize()
 {
 }
```

**Comment by allanmcarvalho** [comment]
Remember that you must call the full Trait path after the namespace. Same example:

```
namespace App\Controller;

use DataTables\Controller\DataTablesAjaxRequestTrait;

class ExampleController extends AppController
```

**Comment by victorpy** [comment]
yes, my controller is:
```

use DataTables\Controller\DataTablesAjaxRequestTrait;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 */
class UsersController extends AppController
{
	
	use DataTablesAjaxRequestTrait;
	public function initialize()
    {
        parent::initialize();
        $this->loadComponent('DataTables.DataTables');
		 $this->DataTables->createConfig('Users')
				->table('Users')
                ->column('Users.username', ['label' => 'Name'])
                ->column('Users.email', ['label' => 'Email'])
                ->column('Users.roles', ['label' => 'roles'])
                ->column('actions', ['label' => 'Actions', 'database' => true]);
    }


....
```

I think the method is implemented but returns a server-side error 500.

What i have right now is:

A UsersController.php
  inside that controller i do all the initialization required ( i think...)
then I have a function view3:
```
 public function view3() { 
		
		 $this->DataTables->setViewVars('Users');
		 
		 //debug($this->DataTables);
	}
```
For function view3 i have a template view3.ctp only with:
```
    
<?= $this->DataTables->render('Users') ?>

```
but i dont know where to put the "Setting the ajax response view ", step 4 in how to use

```

<?php
foreach ($results as $result)
{
    $this->DataTables->prepareData([
        $result->id,
        h($result->name),
        $this->Html->link('Delete', ['action' => 'delete', $result->id])
    ]);
}
echo $this->DataTables->response();
```

**Comment by allanmcarvalho** [comment]
Try it....

You must put it in:
`Template/{Controller}/datatables/{config_name_dashed}.ctp`
In your case, in
`Template/Users/datatables/users.ctp`.

A few tips (if you're not using it yet) to help us find this issue if the tips I gave above do not work.
- Make sure you in debug mode in 'Config / app.php'
- Get the full error inside 'logs / error.log' so that we can see in detail what is happening.

**Comment by allanmcarvalho** [comment]
Ohhh... I see a problem in your configs inside initialize() too.


```
$this->loadComponent('DataTables.DataTables');
		 $this->DataTables->createConfig('Users')
				->table('Users')
                ->column('Users.username', ['label' => 'Name'])
                ->column('Users.email', ['label' => 'Email'])
                ->column('Users.roles', ['label' => 'roles'])
                ->column('actions', ['label' => 'Actions', 'database' => true]);

```

when the column is not a database column, um must set the paramn 'database' to false, not to true...

**Comment by victorpy** [comment]
yes, that was some modification i made when trying to make it work. I will change that to false again.
In debug, i see i had that column problem, that raised the 500 error.
Now i get, the data null, but i think is because the code in Template/Users/datatables/users.ctp, is not matching my column names. I will change that and let you know....

**Comment by victorpy** [comment]
Now is working. Thanks for the help!!
Great tool.
Quick question, do you have some library for inline editing for datatables? The Editor plugin from datatable.org have commercial license. Just in case you know some good one, and free

**Comment by allanmcarvalho** [comment]
Very good, any questions or feedback, please open a issue.

Well, I've seen some, but never used it. But I know that with dedication and a little curiosity you can find some or even develop something of your own. In these cases, I've never edited directly into the table, I just edited with a ajax modal, and asked the datatable 'js' to do a redraw of that data page. I see this form as the simplest to do.
